### ISSUE TITLE
Enhance the cart sidebar on menu page

### ISSUE THREAD

**Issue by Kavyam172** [Open-Source-Chandigarh/Cafe-Management#11]
The design for the cart sidebar on the menu page needs enhancement

**Comment by sukuasoft** [comment]
@Kavyam172 
How to work on this issue?
@aosccode

**Comment by tharanithar-r** [comment]
I am interested in working on this issue. Kindly assign it to me. I am contributing under Hacktoberfest so please add hacktoberfest label.

**Comment by Kavyam172** [comment]
@sukuasoft I am not sure what you are asking but if you want to know how to contribute, you can refer to the 'Readme.md' file.

**Comment by Kavyam172** [comment]
@tharanithar-r I am assigning this issue to you.
