### ISSUE TITLE
Add description in Readme

### ISSUE THREAD

**Issue by Kavyam172** [Open-Source-Chandigarh/Cafe-Management#21]
Add some description about the project, its features, what it aims to do, how it can be used, etc.

**Comment by alok5050** [comment]
Hey, I am interested in this issue. Can you please assign me this issue?

**Comment by SanjanaReddy7707** [comment]
Hey @Kavyam172 
I've previously worked on this project and made contributions. I'd be happy to help out by improving the README file.

**Comment by Kavyam172** [comment]
@alok5050 I am assigning this issue to you.

**Comment by siya100** [comment]
hey @Kavyam172 
can you please assign me this issue

**Comment by rudrakushwaha** [comment]
hey @Kavyam172 can I work on it?

**Comment by Kavyam172** [comment]
@siya100 Are you working on this issue?

**Comment by BowlPulp** [comment]
If the user is not working on the issue, I would love to work on it! Would provide you the solution within 12 hours at max!

**Comment by Kavyam172** [comment]
@BowlPulp Go ahead.

**Comment by BowlPulp** [comment]
Done! https://github.com/Open-Source-Chandigarh/Cafe-Management/pull/51
