### ISSUE TITLE
"Forgot Password" link missing in login page

### ISSUE THREAD

**Issue by Srishdwi02** [Open-Source-Chandigarh/Cafe-Management#23]
The login page does not have forgot password link.
![Screenshot 2023-10-24 233018](https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/138107242/6a622eed-80f6-4be3-acaa-1d329e6f7fc6)

**Comment by SanjanaReddy7707** [comment]
@Srishdwi02 @Kavyam172 
I would like to work on this issue
can u plz assign it to me
thank you!

**Comment by Kavyam172** [comment]
@Srishdwi02 I am assigning this issue to you.

**Comment by Srishdwi02** [comment]
thankyou @Kavyam172
