### ISSUE TITLE
Enhance the checkout page, 

### ISSUE THREAD

**Issue by Light13008** [Open-Source-Chandigarh/Cafe-Management#25]
I can improve the design and the User Experience of the check-out page, where other details are to be put.

Please assign this issue to me.
![WhatsApp Image 2023-10-25 at 10 38 49_295b78f8](https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/111660124/f22ad8c3-607a-4c3a-ab87-3b4b4eac02c2)

**Comment by Kavyam172** [comment]
@Light13008 Go ahead with your changes.
