### ISSUE TITLE
Improve the User Interface of 'Contact Us' page

### ISSUE THREAD

**Issue by Light13008** [Open-Source-Chandigarh/Cafe-Management#32]
![image](https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/111660124/0372204d-b4a2-46ad-bfb2-e5517b947c22)

align the input fields and the name uniformly.
adjust the width of button.

**Comment by Sneha-S-D** [comment]
i can work on it

**Comment by Kavyam172** [comment]
@Sneha-S-D I am assigning this issue to you
