### ISSUE TITLE
[Enhancement] : Better UI for menu

### ISSUE THREAD

**Issue by chaitanyakatore** [Open-Source-Chandigarh/Cafe-Management#49]
- UI of menu is not user friendly
- element of menu is not clearly visible
- assign me this under hacktoberfest I will make it simple and  visible

<img width="1440" alt="Screenshot 2023-10-29 at 11 35 06 PM" src="https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/106269976/e1b8cdc8-b406-42e5-b265-c27ac01abe4f">

**Comment by Kavyam172** [comment]
@chaitanyakatore An issue regarding this already exists.
