### ISSUE TITLE
Uneccesary scroll bar on homepage

### ISSUE THREAD

**Issue by ChauhanGauri** [Open-Source-Chandigarh/Cafe-Management#59]
The home page has a vertical scroll bar which is not needed . I would like to resolve the issue  . Kindly assign it to me under hacktober fest if applicable.
![The Cafe - Google Chrome 10_11_2024 8_11_58 PM](https://github.com/user-attachments/assets/b18f8c87-4072-41e0-86b5-3f11a06c41fc)

**Comment by Mayank-joshi-21** [comment]
The issue was resolved. 
![Screenshot (424)](https://github.com/user-attachments/assets/b8edd0fe-d54b-4e95-ada7-6777edb4f1df)
