### ISSUE TITLE
layout issues at menu.html menu table.

### ISSUE THREAD

**Issue by lovishGIT** [Open-Source-Chandigarh/Cafe-Management#6]
The part of table where we add or delete in our order, Flex box need to be introduced. 
![image](https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/127772046/766d12ec-6fdc-4a22-a2c9-cbebd0ec9982)

This layout is a quick fix and may add simplicity to your website.

**Comment by lovishGIT** [comment]
https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/127772046/e222efde-e09f-4623-ab0b-adf7e54214d2

**Comment by Kavyam172** [comment]
@lovishGIT I am assigning this issue to you.
