### ISSUE TITLE
Step 1 Area need to be a clickable and should directly be taking you to menu.html

### ISSUE THREAD

**Issue by lovishGIT** [Open-Source-Chandigarh/Cafe-Management#7]
it should say Your cart is empty Go to Menu, when no items are in cart. but here it just appears to be blank.
![image](https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/127772046/b8d1f725-ef03-41d2-bfc7-a82d71516a80)
One more quick fix.
This area need to be a linking to your menu.html

**Comment by lovishGIT** [comment]
https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/127772046/593b84f0-f5a2-459c-b813-977bf14991f5

**Comment by lovishGIT** [comment]
https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/127772046/d77a61c4-752d-4833-9bf5-2bae97de5aa0

**Comment by lovishGIT** [comment]
https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/127772046/a8d9a9e6-2533-406f-8ce9-8464a1719711

**Comment by Kavyam172** [comment]
@lovishGIT I am assigning you this issue.
