### ISSUE TITLE
Add login and signup pages

### ISSUE THREAD

**Issue by Kavyam172** [Open-Source-Chandigarh/Cafe-Management#8]

**Comment by sukuasoft** [comment]
@Kavyam172 How to work on this issue?
@aosccode?

**Comment by Prithvi-R** [comment]
Please give some description of the issue

**Comment by Kavyam172** [comment]
@sukuasoft I am not sure what you are asking but if you want to know how to contribute, you can refer to the 'Readme.md' file.

**Comment by Kavyam172** [comment]
@Prithvi-R You have to add a login and a sign up page to the website. 
Also add the links to those pages on the navbar.

**Comment by SanjanaReddy7707** [comment]
@Kavyam172  
I am interested to work on this 
can you please asssign this to me
thank you!!

**Comment by Kavyam172** [comment]
@SanjanaReddy7707 I am assigning this issue to you.
